bath:
    path: http://127.0.0.1:9001/sipsd-flow-modeler
log:
    level: INFO
    path: classpath:applogs\flow
    root: DEBUG

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/flowable_test?characterEncoding=UTF-8&useUnicode=true&useSSL=false
        username: root
        password: 123@abcd
        hikari:
            auto-commit: true
            cachePrepStmts: true
            connection-test-query: SELECT 1
            connection-timeout: 30000
            idle-timeout: 600000
            max-lifetime: 28740000
            maximum-pool-size: 20
            minimum-idle: 5
            pool-name: DatebookHikariCP
            prepStmtCacheSize: 300
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true
info: 
    app:  
        name: "@project.name@"
        description: "@project.description@"  
        version: "@project.version@"  
        spring-boot-version: "@project.parent.version@"
security :
    basic :
        enabled:false
sipsd:
    flowable:
        calendar: false
        approveState: false
        approveKey: approve
#License相关配置
#license:
#    subject: dpark_license
#    publicAlias: publicCert
#    storePass: public_passwordQAZ2wsx3edc
#    licensePath: /Users/mac/Documents/Apache/license_demo/license.lic
#    public-keys-store-path: /Users/mac/Documents/Apache/license_demo/publicCerts.keystore
#    app-id: 123