app:
  name: sipsd-flow-modeler
flowable:
  activityFontName: 宋体
  annotationFontName: 宋体
  common:
    app:
      idm-url: ${bath.path}/idm
      role-prefix: ''
  database-schema-update: true
  labelFontName: 宋体
  modeler:
    app:
      rest-enabled: true
  process:
    definition-cache-limit: 1
  rest:
    app:
      authentication-mode: verify-privilege
  xml:
    encoding: UTF-8
management:
  endpoint:
    health:
      roles: access-admin
      show-details: when_authorized
  endpoints:
    jmx:
      unique-names: true
    web:
      exposure:
        include: '*'
        
mybatis-plus:
  #config-location: classpath:/META-INF/mybatis-config.xml
  mapper-locations: classpath:/META-INF/sipsd-mybatis-mappings/*/xml/*.xml,classpath:/META-INF/modeler-mybatis-mappings/*.xml
  configuration-properties:
    blobType: BLOB
    boolValue: true
    prefix: ''
  #configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 4096
  port: 9001
  servlet:
    context-path: /sipsd-flow-modeler
  tomcat:
    uri-encoding: UTF-8
spring:
  aop:
    auto: false
    proxy-target-class: false
  application:
    name: sipsd-flow-modeler
  banner:
    location: classpath:sipsd-banner.txt
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jmx:
    default-domain: ${spring.application.name}
  liquibase:
    enabled: false
  mvc:
    favicon:
      enabled: false
  security:
    filter:
      dispatcher-types: REQUEST,FORWARD,ASYNC
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active: hotline
