bath:
    path: http://127.0.0.1:9001/sipsd-flow-modeler
log:
    level: INFO
    path: classpath:applogs\flow
    root: DEBUG

spring:
    endpoints:
        sensitive: false     
    datasource:
        druid:
            initial-size: 10
            max-active: 40
            max-pool-prepared-statement-per-connection-size: 20
            max-wait: 60000
            min-evictable-idle-time-millis: 300000
            min-idle: 5
            pool-prepared-statements: true
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 60000
            #url:  jdbc:mysql://115.28.187.78:3306/sipsd-simple?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#            url:  jdbc:mysql://115.28.187.78:3306/flowable?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#            username: root
#            password: Admin@1234
            url: jdbc:mysql://cdb-eqybbrkx.gz.tencentcdb.com:10150/flowable_v4?characterEncoding=UTF-8&useUnicode=true&useSSL=false
            username: root
            password: gao1210886745
            driver-class-name: com.mysql.jdbc.Driver
            validation-query: SELECT 1
            show-sql: true
            filter:
                commons-log:
                    data-source-log-enabled: true
                    statement-log-enabled: true
                    statement-executable-sql-log-enable: true

info: 
    app:  
        name: "@project.name@"
        description: "@project.description@"  
        version: "@project.version@"  
        spring-boot-version: "@project.parent.version@"
security : 
    basic :
        enabled:false